spring:
    datasource:
        url: jdbc:mysql://localhost:3306/springdesk
        username: neo
        password: zero81
        driver-class-name: com.mysql.jdbc.Driver
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
            dialect: org.hibernate.dialect.MySQL8Dialect
    thymeleaf:
        cache: false
server:
  error:
    whitelabel:
      enabled: false