spring:
    datasource:
        url: jdbc:mysql://localhost:3306/springdesk
        username: neo
        password: zero81
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
            dialect: org.hibernate.dialect.MySQL8Dialect
    thymelaf:
        cache: false